openapi: 3.0.0
info:
  title: ApigeeDemo
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
paths:
  /mocktest:
    get:
      tags:
        - General
      summary: Mock Request
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth:
    get:
      tags:
        - General
      summary: Mock Request Basic Auth
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
